spring:
  application:
    name= momoolggo
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DATASOURCE.DB_URL}
    username: ${DATASOURCE.USERNAME}
    password: ${DATASOURCE.PASSWORD}


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml
